<?php

// $Author: beckmi $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
// Author: Simon Roberts (AKA wishcraft)                                     //
// URL: http://www.chronolabs.org.au                                         //
// Project: The XOOPS Project                                                //
// ------------------------------------------------------------------------- //

$modversion['name'] = _MI_MAQUEE_NAME;
$modversion['version'] = 1.03;
$modversion['releasedate'] = "Monday: September 13, 2011";
$modversion['description'] = _MI_MAQUEE_DESCRIPTION;
$modversion['author'] = "Wishcraft";
$modversion['credits'] = "Simon Roberts (simon@chronolabs.coop)";
$modversion['help'] = "maquee.html";
$modversion['license'] = "GPL";
$modversion['official'] = 0;
$modversion['status']  = "Stable";
$modversion['image'] = "images/maquee_slogo.png";
$modversion['dirname'] = _MI_MAQUEE_DIRNAME;
$modversion['hasMain'] = 1;

$modversion['author_realname'] = "Simon Roberts";
$modversion['author_website_url'] = "http://www.chronolabs.coop";
$modversion['author_website_name'] = "Chronolabs Cooperative";
$modversion['author_email'] = "simon@chronolabs.coop";
$modversion['demo_site_url'] = "http://xoops.demo.chronolabs.coop";
$modversion['demo_site_name'] = "Chronolabs Co-op XOOPS Demo";
$modversion['support_site_url'] = "";
$modversion['support_site_name'] = "Chronolabs";
$modversion['submit_bug'] = "";
$modversion['submit_feature'] = "";
$modversion['usenet_group'] = "sci.chronolabs";
$modversion['maillist_announcements'] = "";
$modversion['maillist_bugs'] = "";
$modversion['maillist_features'] = "";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Main things
$modversion['hasMain'] = 1;

//$modversion['onUpdate'] = "include/update.php";
//$modversion['onInstall'] = "include/install.php";
//$modversion['onUninstall'] = "include/uninstall.php";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// $modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "maquee_maquees";
$modversion['tables'][1] = "maquee_gallery";
$modversion['tables'][2] = "maquee_text";

// Blocks
$modversion['blocks'][1]['file'] = "maquee_block_maquee.php";
$modversion['blocks'][1]['name'] = 'Maquee' ;
$modversion['blocks'][1]['description'] = "Shows maquee";
$modversion['blocks'][1]['show_func'] = "b_maquee_block_maquee_show";
$modversion['blocks'][1]['edit_func'] = "b_maquee_block_maquee_edit";
$modversion['blocks'][1]['options'] = "0";
$modversion['blocks'][1]['template'] = "maquee_block_maquee.html" ;

// Templates
$modversion['templates'][1]['file'] = 'maquee_index.html';
$modversion['templates'][1]['description'] = 'Main Index for Maquee';
$modversion['templates'][2]['file'] = 'maquee_maquee.html';
$modversion['templates'][2]['description'] = 'Main Gallery Maquee';
$modversion['templates'][3]['file'] = 'maquee_cpanel_maquee_list.html';
$modversion['templates'][3]['description'] = 'Main Control Panel Maquee List';
$modversion['templates'][4]['file'] = 'maquee_cpanel_maquee_edit.html';
$modversion['templates'][4]['description'] = 'Main Control Panel Macquee Edit';
$modversion['templates'][5]['file'] = 'maquee_cpanel_gallery_list.html';
$modversion['templates'][5]['description'] = 'Main Control Panel Gallery List';
$modversion['templates'][6]['file'] = 'maquee_cpanel_gallery_edit.html';
$modversion['templates'][6]['description'] = 'Main Control Panel Gallery Edit';
$modversion['templates'][7]['file'] = 'maquee_cpanel_text_list.html';
$modversion['templates'][7]['description'] = 'Main Control Panel Text Ticker List';
$modversion['templates'][8]['file'] = 'maquee_cpanel_text_edit.html';
$modversion['templates'][8]['description'] = 'Main Control Panel Twitter Bomb Text Ticker Edit';

$i = 0;
xoops_load('XoopsEditorHandler');
$editor_handler = XoopsEditorHandler::getInstance();
foreach ($editor_handler->getList(false) as $id => $val)
	$options[$val] = $id;
	
$i++;
$modversion['config'][$i]['name'] = 'editor';
$modversion['config'][$i]['title'] = "_MI_MAQUEE_EDITOR";
$modversion['config'][$i]['description'] = "_MI_MAQUEE_EDITOR_DESC";
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'tinymce';
$modversion['config'][$i]['options'] = $options;

$i++;
$modversion['config'][$i]['name'] = 'default_animation';
$modversion['config'][$i]['title'] = "_MI_MAQUEE_DEFAULT_ANIMATION_TYPE";
$modversion['config'][$i]['description'] = "_MI_MAQUEE_DEFAULT_ANIMATION_TYPE_DESC";
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['options'] = array(_MI_MAQUEE_DEFAULT_ANIMATION_TYPE_SLIDEUP=>'slideup', _MI_MAQUEE_DEFAULT_ANIMATION_TYPE_FADEIN=>'fadein',_MI_MAQUEE_DEFAULT_ANIMATION_TYPE_SLIDEDOWN=>'slidedown', _MI_MAQUEE_DEFAULT_ANIMATION_TYPE_FADEOUT=>'fadeout', _MI_MAQUEE_DEFAULT_ANIMATION_TYPE_RANDOM=>'random');
$modversion['config'][$i]['default'] = 'fadein';

$i++;
$modversion['config'][$i]['name'] = 'default_sequence';
$modversion['config'][$i]['title'] = "_MI_MAQUEE_DEFAULT_SEQUENCE";
$modversion['config'][$i]['description'] = "_MI_MAQUEE_DEFAULT_SEQUENCE_DESC";
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['options'] = array(_MI_MAQUEE_DEFAULT_SEQUENCE_SEQUENCE=>'sequence', _MI_MAQUEE_DEFAULT_SEQUENCE_RANDOM=>'random', _MI_MAQUEE_DEFAULT_SEQUENCE_RANDOM_START=>'random_start');
$modversion['config'][$i]['default'] = 'sequence';

$i++;
$modversion['config'][$i]['name'] = 'default_speed';
$modversion['config'][$i]['title'] = "_MI_MAQUEE_DEFAULT_SPEED";
$modversion['config'][$i]['description'] = "_MI_MAQUEE_DEFAULT_SPEED_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 2200;

$i++;
$modversion['config'][$i]['name'] = 'default_timeout';
$modversion['config'][$i]['title'] = "_MI_MAQUEE_DEFAULT_TIMEOUT";
$modversion['config'][$i]['description'] = "_MI_MAQUEE_DEFAULT_TIMEOUT_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 7500;

$i++;
$modversion['config'][$i]['name'] = 'default_width';
$modversion['config'][$i]['title'] = "_MI_MAQUEE_DEFAULT_WIDTH";
$modversion['config'][$i]['description'] = "_MI_MAQUEE_DEFAULT_WIDTH_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 960;

$i++;
$modversion['config'][$i]['name'] = 'default_height';
$modversion['config'][$i]['title'] = "_MI_MAQUEE_DEFAULT_HEIGHT";
$modversion['config'][$i]['description'] = "_MI_MAQUEE_DEFAULT_HEIGHT_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 455;

$i++;
$modversion['config'][$i]['name'] = 'uploaddir';
$modversion['config'][$i]['title'] = '_MI_MAQUEE_UPLOADDIR';
$modversion['config'][$i]['description'] = '_MI_MAQUEE_UPLOADDIR_DESC';
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = XOOPS_ROOT_PATH.DIRECTORY_SEPARATOR.'uploads'.DIRECTORY_SEPARATOR.'maquee';

$i++;
$modversion['config'][$i]['name'] = 'scale_images';
$modversion['config'][$i]['title'] = '_MI_MAQUEE_SCALE_IMAGES';
$modversion['config'][$i]['description'] = '_MI_MAQUEE_SCALE_IMAGES_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = true;

$i++;
$modversion['config'][$i]['name'] = 'auto_crop_images';
$modversion['config'][$i]['title'] = '_MI_MAQUEE_AUTO_CROP_IMAGES';
$modversion['config'][$i]['description'] = '_MI_MAQUEE_AUTO_CROP_IMAGES_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = true;

$i++;
$modversion['config'][$i]['name'] = 'css';
$modversion['config'][$i]['title'] = '_MI_MAQUEE_CSS';
$modversion['config'][$i]['description'] = '_MI_MAQUEE_CSS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = "list-style:none;\nlist-style-position:inside;\nlist-style-type:none;\nmargin: 0px 0px 0px 0px;\npadding: 0px 0px 0px 0px;";

$i++;
$modversion['config'][$i]['name'] = 'allowed_file_extensions';
$modversion['config'][$i]['title'] = '_MI_MAQUEE_ALLOWED_FILE_EXTENSION';
$modversion['config'][$i]['description'] = '_MI_MAQUEE_ALLOWED_FILE_EXTENSION_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = "jpg|jpeg|png|gif";

$i++;
$modversion['config'][$i]['name'] = 'allowed_mimetypes';
$modversion['config'][$i]['title'] = '_MI_MAQUEE_ALLOWED_MIMETYPES';
$modversion['config'][$i]['description'] = '_MI_MAQUEE_ALLOWED_MIMETYPES_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = "image/jpeg|image/pjpeg|image/png|image/gif";

$i++;
$modversion['config'][$i]['name'] = 'maximum_filesize';
$modversion['config'][$i]['title'] = '_MI_MAQUEE_MAXIMUM_FILESIZE';
$modversion['config'][$i]['description'] = '_MI_MAQUEE_MAXIMUM_FILESIZE_DESC';
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1024*1024*2.5;

$i++;
$modversion['config'][$i]['name'] = 'thumbnail_width';
$modversion['config'][$i]['title'] = '_MI_MAQUEE_THUMBNAIL_WIDTH';
$modversion['config'][$i]['description'] = '_MI_MAQUEE_THUMBNAIL_WIDTH_DESC';
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 140;

$i++;
$modversion['config'][$i]['name'] = 'thumbnail_height';
$modversion['config'][$i]['title'] = '_MI_MAQUEE_THUMBNAIL_HEIGHT';
$modversion['config'][$i]['description'] = '_MI_MAQUEE_THUMBNAIL_HEIGHT_DESC';
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 140;

$i++;
$modversion['config'][$i]['name'] = 'force_jquery';
$modversion['config'][$i]['title'] = '_MI_MAQUEE_FORCE_JQUERY';
$modversion['config'][$i]['description'] = '_MI_MAQUEE_FORCE_JQUERY_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = true;

?>
